spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/storedb?createDatabaseIfNotExist=true
    username: storeuser
    password: storepassword
  jpa:
    show-sql: true