spring:
  application:
    name: store

  datasource:
    url: jdbc:mysql://localhost:3306/storedb?createDatabaseIfNotExist=true
    username: storeuser
    password: storepassword

payment:
  provider: stripe

stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD, EUR, GBP
